######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 27 15:05:08 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
MOC_DIR=moc
INCLUDEPATH += .
CONFIG+=static
CONFIG+=release

# Input
HEADERS += mainwindow.h
FORMS += wd.ui
SOURCES += main.cpp mainwindow.cpp
